name: robonomics-benchmarks
on:
  push:
    branches:
    - master

jobs:
  binary:
    name: Benchmark binary 
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2022-04-05
        components: rustfmt, clippy
        default: true

    - name: Install WASM target (for runtime building)
      run: rustup target add wasm32-unknown-unknown --toolchain nightly-2022-04-05

    - name: Build optimized binary
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --locked --no-default-features --features benchmarks

    - name: Upload build artifacts
      uses: actions/upload-artifact@master
      with:
        name: robonomics-benchmarks
        path: target/release/robonomics
