name: Tests
on:
  push:
    branches:
    - '**'
    tags-ignore:
    - v[0-9]+.[0-9]+.[0-9]+*
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  tests:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Install deps
      run: sudo apt -y install protobuf-compiler

    - name: Install & display rust toolchain
      run: rustup show

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - name: All tests
      run: cargo test --all
